name: El filo
siteurl: http://blog.elfilo.net
markdown: redcarpet
permalink: /:title/
pygments: true
excerpt_separator: <!--more--> 
prose:
  siteurl: 'http://blog.elfilo.net/'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "post"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Áreas formativas"
          placeholder: "Elige áreas"
          options:
            - name: "Drupal"
              value: "Drupal"
            - name: "js"
              value: "js"
      - name: "imagen-ficha"
        field:
          element: "text"
          label: "Imagen para la ficha"
          value: ""
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
